/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a one-time password via email */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login-with-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login using an email and the received OTP */
        post: operations["loginWithOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh token cookie */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user and invalidate refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tasks for the authenticated user */
        get: operations["getTasks"];
        put?: never;
        /** Create a new task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /** Update a task */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/recurring-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recurring tasks for the authenticated user
         * @description Returns all recurring tasks owned by the authenticated user.
         */
        get: operations["getRecurringTasks"];
        put?: never;
        /**
         * Create a new recurring task
         * @description Creates a daily, weekly, or monthly recurring task.
         */
        post: operations["createRecurringTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-tasks/{recurringTaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single recurring task */
        get: operations["getRecurringTask"];
        put?: never;
        post?: never;
        /** Delete a recurring task */
        delete: operations["deleteRecurringTask"];
        options?: never;
        head?: never;
        /**
         * Update a recurring task
         * @description Updates title, description, status, or frequency of a recurring task.
         */
        patch: operations["updateRecurringTask"];
        trace?: never;
    };
    "/recurring-task-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recurring task progress for the authenticated user
         * @description Returns the global streak counter for recurring tasks.
         */
        get: operations["getRecurringTaskProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OTPRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example 123456 */
            otp: string;
        };
        LoginResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
        };
        ErrorResponse: {
            /** @example 400 */
            statusCode?: number;
            /** @example Bad Request */
            error?: string;
            /** @example body/email must match format "email" */
            message?: string;
        };
        /** @enum {string} */
        TaskStatus: "todo" | "in_progress" | "review" | "done";
        /** @enum {string} */
        TaskPriority: "none" | "important" | "urgent" | "important_urgent";
        Task: {
            /** Format: uuid */
            id: string;
            /** @example My urgent task */
            title: string;
            /** @example Fix login bug when access token expires */
            description?: string | null;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /**
             * Format: date-time
             * @example 2026-05-10T00:00:00.000Z
             */
            deadline?: string | null;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTaskRequest: {
            /** @example Login testen */
            title: string;
            description?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /** Format: date-time */
            deadline?: string | null;
        };
        UpdateTaskRequest: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /** Format: date-time */
            deadline?: string | null;
        };
        /**
         * @description Status of a recurring task. Recurring tasks do not have review.
         * @enum {string}
         */
        RecurringTaskStatus: "todo" | "in_progress" | "done";
        /**
         * @description Defines how often the task repeats.
         * @enum {string}
         */
        RecurringFrequency: "daily" | "weekly" | "monthly";
        RecurringTask: {
            /** Format: uuid */
            id: string;
            /** @example Learning German */
            title: string;
            /** @example Reading or writing for 30 minutes */
            description?: string | null;
            status: components["schemas"]["RecurringTaskStatus"];
            frequency: components["schemas"]["RecurringFrequency"];
            /**
             * @description Number of successful repetitions in a row.
             * @example 7
             */
            streakCount: number;
            /**
             * Format: date-time
             * @description Last time this recurring task was marked as done.
             * @example 2026-06-06T18:30:00.000Z
             */
            lastCompletedAt?: string | null;
            /**
             * Format: date-time
             * @description Last time the backend reset this task back to todo.
             * @example 2026-06-07T00:00:00.000Z
             */
            lastResetAt?: string | null;
            /**
             * Format: date-time
             * @description Next planned reset time calculated by the backend.
             * @example 2026-06-07T00:00:00.000Z
             */
            nextResetAt: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateRecurringTaskRequest: {
            /** @example Learning German */
            title: string;
            /** @example Reading or writing for 30 minutes */
            description?: string | null;
            frequency: components["schemas"]["RecurringFrequency"];
        };
        UpdateRecurringTaskRequest: {
            /** @example Learning German */
            title?: string;
            description?: string | null;
            status?: components["schemas"]["RecurringTaskStatus"];
            frequency?: components["schemas"]["RecurringFrequency"];
        };
        RecurringTaskProgress: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /**
             * @description Number of periods in a row where all recurring tasks were completed.
             * @example 4
             */
            allTasksStreak: number;
            /**
             * Format: date-time
             * @description Last time the backend checked whether all recurring tasks were completed.
             * @example 2026-06-07T00:00:00.000Z
             */
            lastCheckedAt?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequest"];
            };
        };
        responses: {
            /** @description OTP successfully sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OTP sent to your email */
                        message?: string;
                    };
                };
            };
            /** @description Bad Request (e.g. invalid email format) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginWithOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OTP verified and access token generated. A refresh token cookie is set. */
            200: {
                headers: {
                    /** @description HttpOnly refresh token cookie (refreshToken=...; HttpOnly; Secure; SameSite=...) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid or expired OTP */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token issued. Refresh token cookie may be rotated. */
            200: {
                headers: {
                    /** @description HttpOnly refresh token cookie (refreshToken=...; HttpOnly; Secure; SameSite=...) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Missing, invalid, or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out. Refresh token cookie is cleared. */
            204: {
                headers: {
                    /** @description Clears the refresh token cookie (refreshToken=; Max-Age=0; ...) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid refresh token provided */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecurringTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recurring tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTask"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRecurringTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringTaskRequest"];
            };
        };
        responses: {
            /** @description Recurring task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTask"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecurringTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurringTaskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTask"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Recurring task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteRecurringTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurringTaskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring task deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateRecurringTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurringTaskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringTaskRequest"];
            };
        };
        responses: {
            /** @description Recurring task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTask"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Recurring task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecurringTaskProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring task progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTaskProgress"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
